export const objects = [
    {
        "name": "smallCRed1",
        "colour": "red",
        "shape": "circle",
        "size": "small",
    },
    {
        "name": "smallCRed2",
        "colour": "red",
        "shape": "circle",
        "size": "small",
    },
    {
        "name": "smallCOrange1",
        "colour": "orange",
        "shape": "circle",
        "size": "small",
    },
    {
        "name": "smallCOrange2",
        "colour": "orange",
        "shape": "circle",
        "size": "small",
    },
    {
        "name": "smallCGreen1",
        "colour": "green",
        "shape": "circle",
        "size": "small",
    },
    {
        "name": "smallCGreen2",
        "colour": "green",
        "shape": "circle",
        "size": "small",
    },
    {
        "name": "mediumCRed1",
        "colour": "red",
        "shape": "circle",
        "size": "medium",
    },
    {
        "name": "mediumCRed2",
        "colour": "red",
        "shape": "circle",
        "size": "medium",
    },
    {
        "name": "mediumCOrange1",
        "colour": "orange",
        "shape": "circle",
        "size": "medium",
    },
    {
        "name": "mediumCOrange2",
        "colour": "orange",
        "shape": "circle",
        "size": "medium",
    },
    {
        "name": "mediumCGreen1",
        "colour": "green",
        "shape": "circle",
        "size": "medium",
    },
    {
        "name": "mediumCGreen2",
        "colour": "green",
        "shape": "circle",
        "size": "medium",
    },
    {
        "name": "largeCRed1",
        "colour": "red",
        "shape": "circle",
        "size": "large",
    },
    {
        "name": "largeCRed2",
        "colour": "red",
        "shape": "circle",
        "size": "large",
    },
    {
        "name": "largeCOrange1",
        "colour": "orange",
        "shape": "circle",
        "size": "large",
    },
    {
        "name": "largeCOrange2",
        "colour": "orange",
        "shape": "circle",
        "size": "large",
    },
    {
        "name": "largeCGreen1",
        "colour": "green",
        "shape": "circle",
        "size": "large",
    },
    {
        "name": "largeCGreen2",
        "colour": "green",
        "shape": "circle",
        "size": "large",
    },
    {
        "name": "smallRRed1",
        "colour": "red",
        "shape": "rectangle",
        "size": "small",
    },
    {
        "name": "smallRRed2",
        "colour": "red",
        "shape": "rectangle",
        "size": "small",
    },
    {
        "name": "smallROrange1",
        "colour": "orange",
        "shape": "rectangle",
        "size": "small",
    },
    {
        "name": "smallROrange2",
        "colour": "orange",
        "shape": "rectangle",
        "size": "small",
    },
    {
        "name": "smallRGreen1",
        "colour": "green",
        "shape": "rectangle",
        "size": "small",
    },
    {
        "name": "smallRGreen2",
        "colour": "green",
        "shape": "rectangle",
        "size": "small",
    },
    {
        "name": "mediumRRed1",
        "colour": "red",
        "shape": "rectangle",
        "size": "medium",
    },
    {
        "name": "mediumRRed2",
        "colour": "red",
        "shape": "rectangle",
        "size": "medium",
    },
    {
        "name": "mediumROrange1",
        "colour": "orange",
        "shape": "rectangle",
        "size": "medium",
    },
    {
        "name": "mediumROrange2",
        "colour": "orange",
        "shape": "rectangle",
        "size": "medium",
    },
    {
        "name": "mediumRGreen1",
        "colour": "green",
        "shape": "rectangle",
        "size": "medium",
    },
    {
        "name": "mediumRGreen2",
        "colour": "green",
        "shape": "rectangle",
        "size": "medium",
    },
    {
        "name": "largeRRed1",
        "colour": "red",
        "shape": "rectangle",
        "size": "large",
    },
    {
        "name": "largeRRed2",
        "colour": "red",
        "shape": "rectangle",
        "size": "large",
    },
    {
        "name": "largeROrange1",
        "colour": "orange",
        "shape": "rectangle",
        "size": "large",
    },
    {
        "name": "largeROrange2",
        "colour": "orange",
        "shape": "rectangle",
        "size": "large",
    },
    {
        "name": "largeRGreen1",
        "colour": "green",
        "shape": "rectangle",
        "size": "large",
    },
    {
        "name": "largeRGreen2",
        "colour": "green",
        "shape": "rectangle",
        "size": "large",
    },
    {
        "name": "smallSRed1",
        "colour": "red",
        "shape": "square",
        "size": "small",
    },
    {
        "name": "smallSRed2",
        "colour": "red",
        "shape": "square",
        "size": "small",
    },
    {
        "name": "smallSOrange1",
        "colour": "orange",
        "shape": "square",
        "size": "small",
    },
    {
        "name": "smallSOrange2",
        "colour": "orange",
        "shape": "square",
        "size": "small",
    },
    {
        "name": "smallSGreen1",
        "colour": "green",
        "shape": "square",
        "size": "small",
    },
    {
        "name": "smallSGreen2",
        "colour": "green",
        "shape": "square",
        "size": "small",
    },
    {
        "name": "mediumSRed1",
        "colour": "red",
        "shape": "square",
        "size": "medium",
    },
    {
        "name": "mediumSRed2",
        "colour": "red",
        "shape": "square",
        "size": "medium",
    },
    {
        "name": "mediumSOrange1",
        "colour": "orange",
        "shape": "square",
        "size": "medium",
    },
    {
        "name": "mediumSOrange2",
        "colour": "orange",
        "shape": "square",
        "size": "medium",
    },
    {
        "name": "mediumSGreen1",
        "colour": "green",
        "shape": "square",
        "size": "medium",
    },
    {
        "name": "mediumSGreen2",
        "colour": "green",
        "shape": "square",
        "size": "medium",
    },
    {
        "name": "largeSRed1",
        "colour": "red",
        "shape": "square",
        "size": "large",
    },
    {
        "name": "largeSRed2",
        "colour": "red",
        "shape": "square",
        "size": "large",
    },
    {
        "name": "largeSOrange1",
        "colour": "orange",
        "shape": "square",
        "size": "large",
    },
    {
        "name": "largeSOrange2",
        "colour": "orange",
        "shape": "square",
        "size": "large",
    },
    {
        "name": "largeSGreen1",
        "colour": "green",
        "shape": "square",
        "size": "large",
    },
    {
        "name": "largeSGreen2",
        "colour": "green",
        "shape": "square",
        "size": "large",
    },


]